version: '2'

services:
  node0:
    container_name: node0
    image: nervos/muta:latest
    hostname: node0
    environment:
      - RUST_BACKTRACE
    volumes:
      - ./config-single.toml:/app/devtools/chain/config.toml
      - ../../../target/data/single:/app/devtools/chain/data
    ports:
      - "1337:1337"
      - "8000:8000"
    networks:
      single:
        aliases:
          - node0

networks:
  single:
