# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json
# You can override the valid types

# Angular
types:
    - build # Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
    - ci # Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
    - docs # Documentation only changes
    - feat # A new feature
    - fix # A bug fix
    - perf # A code change that improves performance
    - refactor # A code change that neither fixes a bug nor adds a feature
    - style # Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - test # Adding missing tests or correcting existing tests
