apiVersion: nervos.org/v1alpha1
kind: Muta
metadata:
  name: chaos-${REPO_NAME}-${VERSION}
  namespace: mutadev # Only supports deployment to the mutadev namespace
spec:
  image: mutadev/muta:latest # docker image
  resources:
    limits:
      cpu: 1100m
      memory: 3Gi
      ephemeral-storage: 5Gi
    requests:
      cpu: 1100m
      memory: 3Gi
      ephemeral-storage: 5Gi
  chaos: # all / stable-network-corrupt / stable-network-delay / stable-network-duplicate / stable-network-loss / stable-network-partition / stable-node-failure / stable-node-kill
    - all
  size: 4 # Node numbers
  persistent: false # Persistent data
  config: # see https://github.com/nervosnetwork/muta/blob/master/devtools/chain/config.toml
    data_path: "/app/data"
    graphql:
      listening_address: "0.0.0.0:8000"
      graphql_uri: "/graphql"
      graphiql_uri: "/"
      workers: 0 # if 0, uses number of available logical cpu as threads count.
      maxconn: 25000
    network:
      listening_address: "0.0.0.0:1337"
      rpc_timeout: 10
    mempool:
      pool_size: 20000
      broadcast_txs_size: 200
      broadcast_txs_interval: 200
    executor:
      light: false
    logger:
      filter: "info"
      log_to_console: true
      console_show_file_and_line: false
      log_path: "logs/"
      log_to_file: true
      metrics: true
      modules_level:
        # "overlord::state::process": "debug"
        # "core_consensus": "error"
  genesis: # https://github.com/nervosnetwork/muta/blob/master/devtools/chain/genesis.toml
    prevhash: "0x44915be5b6c20b0678cf05fcddbbaa832e25d7e6ac538784cd5c24de00d47472"
    metadata:
      chain_id: "0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036"
      timeout_gap: 20
      cycles_limit: 99999999
      cycles_price: 1
      interval: 3000
      propose_ratio: 15
      prevote_ratio: 15
      precommit_ratio: 10
      brake_ratio: 3
      tx_num_limit: 20000
     max_tx_size: 1073741824
   services:
     - name: asset
       payload: '{ "id": "0xf56924db538e77bb5951eb5ff0d02b88983c49c45eea30e8ae3e7234b311436c", "name": "MutaToken", "symbol": "MT", "supply": 320000011, "issuer": "muta14e0lmgck835vm2dfm0w3ckv6svmez8fdgdl705" }'
