FROM mutadev/muta:build-env

LABEL maintainer="yejiayu.fe@gmail.com"

WORKDIR /app

COPY . .

RUN make ci
RUN make prod

COPY /app/target/release/examples/muta-chain /app/bin
EXPOSE 1337 8000
CMD ["/app/bin"]
