data_path = "./devtools/chain/data/1"
privkey = "0x4a33067c449635c434cc758ed5f595e1f5653debc45233997c93814c31f710d5"

[network]
listening_address = "0.0.0.0:1337"
rpc_timeout = 10

[graphql]
graphiql_uri = "/graphiql"
listening_address = "0.0.0.0:8000"
graphql_uri = "/graphql"
workers = 0 # if 0, uses number of available logical cpu as threads count.
maxconn = 25000
max_payload_size = 1048576

[executor]
light = false

[mempool]
broadcast_txs_size = 200
broadcast_txs_interval = 200
pool_size = 200000

[logger]
metrics = false
log_path = "./devtools/chain/logs/1"
log_to_console = true
filter = "info"
log_to_file = true
console_show_file_and_line = false

[rocksdb]
max_open_files = 64
