# crypto
privkey = "0x8dbd2f1f1a8fbb97d94f4a79cee67a8b3766057aaa310f2d5ddf3cd73b8a1e3d"

# db config
data_path = "./devtools/chain/data1"

[graphql]
listening_address = "0.0.0.0:8001"
graphql_uri = "/graphql"
graphiql_uri = "/graphiql"
workers = 0 # if 0, uses number of available logical cpu as threads count.
maxconn = 25000
max_payload_size = 1048576

[network]
listening_address = "0.0.0.0:1338"
rpc_timeout = 10

[consensus]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
pubkey = "0x035653c6f91f198fd24b0a7e90fd9486d7c98e77bb2161608faf4e220921be8814"
address = "0.0.0.0:1337"

[mempool]
pool_size = 20000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
light = false

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/"
log_to_file = true
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }
# modules_level = { "core_network" = "debug" }

[rocksdb]
max_open_files = 64
