version: '2'
services:
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command:
      # - '--reporter.grpc.host-port=47.114.157.77:14250'
      - '--reporter.grpc.host-port=${JAEGER_REPORTER_HOST}'
    ports:
      - '14271:14271'
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
    restart: on-failure
    networks:
      - jaeger-agent
  node-exporter:
    image: quay.io/prometheus/node-exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.tcpstat'
    restart: on-failure
    network_mode: 'host'
    pid: 'host'
    volumes:
      - /:/host:ro,rslave
networks:
  jaeger-agent:
    driver: bridge
